# 📌 Programación Orientada a Objetos(POO) en Python
## Autor: Emmanuel ALfaro Brenes
### Fecha: 2025/02/11

##################### NOTEBOOK DE ESTUDIANTE ########################

## Programacion Python Basico | ICAI

## Profesor: Ing. Andrés Mena Abarca

### **Nombre del estudiante: Emmanuel Alfaro Brenes **

#*******************************************************************#

# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiantes: 

### Crear un array a partir de una lista

In [17]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [1]:
#Código crear un array de ceros de tamaño 5x5
import numpy as np

array_ceros = np.zeros((5,5))
print(array_ceros)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [14]:
#Código crear un array de unos de tamaño 3x3

array_unos = np.ones((5,5))

print(array_unos)

TypeError: only integer scalar arrays can be converted to a scalar index

### Crear un array con valores espaciados uniformemente de 0 a 9

In [20]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
import numpy as np

array_linear = np.linspace(0,9,10)
print(array_linear)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [21]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1

array_reto = np.linspace(0,9,50)
print(array_reto)


TypeError: 'numpy.float64' object cannot be interpreted as an integer

# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [ ]:
array_Producto = np.array([5,4,2])
array_Dinero = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''

suma = array_Producto + array_Dinero
resta = array_Producto - array_Dinero
multiplicacion = array_Producto * array_Dinero
division = array_Producto / array_Dinero

print(suma)
print(resta)
print(multiplicacion)
print(division)

In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [ ]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media = np.mea(array_numeros)
print('media aritmetica es', media)

# Calcular la suma
suma = np.sum(array_numeros)
print('suma es igual a:', suma)

# Calcular el valor mínimo
minimo = np.min(array_numeros)
print(minimo)

# Calcular el valor máximo
maximo = np.max(array_numeros)
print(maximo)

'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


AttributeError: module 'numpy' has no attribute 'mea'

In [ ]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_finalshape = array_original.reshape(3,2)
print(array_finalshape)

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



#EJERCICIOS REALES O PRACTICOS


In [ ]:
import numpy as np

persona = np.array([7,9,2])

avatar = np.array([10,1,5]) #mas accion y menos comedia
brave_heart = np.array([8,1,7]) #mas accion y menos accion

#calcular la similitud de cada pelicula con los gustos de persona

similitud_p1 = np.dot(persona, avatar)
similitud_p2 = np.dot(persona, brave_heart)

print('similitud de preferencias', similitud_p1)
print('similitud de preferencias', similitud_p2)

if similitud_p1 > similitud_p2:
    print('recomendamos avatar')
else:
    print('recomendamos braveheart')


#caso estudio relacion

In [24]:
import numpy as np
#Datos Tipo Cambio Dolar Ultimos 10 meses | IPC , metrica mesual


tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.70,109.33,108.85, 109.36,110.39,110.79])


#Calcular coeficiente de correlación
correlacion =  np.corrcoef(tipo_cambio,ipc)[0,1]


print(f'Coeficiente de correlación: {correlacion:2f}')

TypeError: 'str' object cannot be interpreted as an integer

Caso #3 Estudio de horas vs notas

In [ ]:
#Datos: Horas de estudio y Notas Obtenidas

import numpy as np

horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10]) # Horas de estudio
notas = np.array([50,55,60,63,67,72,75,78,81,85]) # Notas Obtenida


#Cálculo crecimiento del promedio del puntuje por hora de estudio
diferencias_notas = np.diff(notas)# Difrencias entre notas consecutivas
incremento_notas = np.mean(diferencias_notas)



print(diferencias_notas)
print(incremento_notas)

#Cálculo crecimiento del promedio del puntuje por hora de estudio
diferencias_notas = np.diff(notas)# Difrencias entre notas consecutivas
incremento_notas = np.average(diferencias_notas)


#Estimación del puntaje si estudio 12 horas
proyeccion_estudio= 12
nota_estimada = (proyeccion_estudio - max(horas_estudio)) * incremento_notas + max(notas)



print(f"El incremento del promedio por cada hora de estudio {incremento_notas:.2f}")
print(nota_estimada)

TypeError: expected a sequence of integers or a single integer, got 'np.float64(3.888888888888889)'